### ISSUE TITLE
[Stopove] Partly error generation issue

### ISSUE THREAD

**Issue by JB243** [bsungwoo/STopover#6]
I have attempted STopover analysis with cell types in the Visium data. Originally, I tried to do the following: 

```python
feature_list = ["Hep","KC","Macrophages","cDC","Chol","Monocytes","pDC", "B", "Endo", "T+NK", "HSC"]
stopover_arr = STopover_arr(sp_data=adata1,
                            feature_names=feature_list,
                            batch_dim=-1, scale_factor=30,
                            min_size=30, thres_per=30, fwhm=2.5,
                            save_path='.', J_count=0)
feature_pairs = pd.DataFrame([(j,k) for i,j in enumerate(feature_list) for k in feature_list[i+1:]])
stopover_arr.topological_similarity(feat_pairs=feature_pairs)
```

Then, I could meet a hanging moment without a promise to be finished.

```python
End of data preparation
Elapsed time: 0.78 seconds 
Calculation of adjacency matrix
  0%|          | 0/1 [00:00<?, ?it/s]
  ```
  
I experienced similar things when I run ligand-receptor (LR) interaction analysis with STopover. I think this problem is occurring in a certain cases, not always. Can you help me identify the possible problems related to the hanging phenomenon, such as error messages alert? Thanks in advance!

**Comment by bsungwoo** [comment]
@JB243 Please configure the parameters as follows. The "hanging" phenomenon you observed could potentially be attributed to the extensive number of bins used for calculating the adjacency matrix. However, I can't be entirely certain because the computation time was reasonable on my computer when the scale_factor was set to 30.

```Python
stopover_arr = STopover_arr(sp_data=arr, 
                            feature_names=feature_list,
                            batch_dim=-1, scale_factor=80, 
                            min_size=80, fwhm=2.5, thres_per=10, 
                            save_path='.', J_count=0)
```
Note: The STopover_arr class is not publicly available in the current STopover main branch but will be in the near future.
